version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: pmo-db-container
    environment:
      POSTGRES_USER: pmo_user
      POSTGRES_PASSWORD: pmo_password
      POSTGRES_DB: pmo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pdinet

  backend:
    image: ghcr.io/luis-acosta/pmo-control-backend:main
    container_name: pmo-backend-container
    environment:
      DATABASE_URL: postgres://pmo_user:pmo_password@db:5432/pmo_db
      PORT: 3001
    depends_on:
      - db
    networks:
      - pdinet
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=pdinet
        - traefik.http.routers.pmo-backend.rule=Host(`api.mto.pdiadvanced.cloud`)
        - traefik.http.routers.pmo-backend.entrypoints=websecure
        - traefik.http.routers.pmo-backend.tls.certresolver=letsencryptresolver
        - traefik.http.services.pmo-backend.loadbalancer.server.port=3001

  frontend:
    image: ghcr.io/luis-acosta/pmo-control-frontend:main
    container_name: pmo-frontend-container
    environment:
      BACKEND_URL: http://backend:3001
    networks:
      - pdinet
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=pdinet
        - traefik.http.routers.pmo-frontend.rule=Host(`mto.pdiadvanced.cloud`)
        - traefik.http.routers.pmo-frontend.entrypoints=websecure
        - traefik.http.routers.pmo-frontend.tls.certresolver=letsencryptresolver
        - traefik.http.services.pmo-frontend.loadbalancer.server.port=3000

volumes:
  postgres_data:

networks:
  pdinet:
    external: true

